from __future__ import annotations

TURNO_TEMPLATE_PATIENT_CONSULTORIO = "PACIENTE_CONSULTORIO"
TURNO_TEMPLATE_TURNO_PATIENT_CONSULTORIO = "TURNO_PACIENTE_CONSULTORIO"
TURNO_TEMPLATE_PATIENT_TURNO_CONSULTORIO = "PACIENTE_TURNO_CONSULTORIO"
TURNO_TEMPLATE_TURNO_CONSULTORIO = "TURNO_CONSULTORIO"

TURNO_TEMPLATE_DEFAULT = TURNO_TEMPLATE_PATIENT_CONSULTORIO
TURNO_TEMPLATE_CHOICES = (
    TURNO_TEMPLATE_PATIENT_CONSULTORIO,
    TURNO_TEMPLATE_TURNO_PATIENT_CONSULTORIO,
    TURNO_TEMPLATE_PATIENT_TURNO_CONSULTORIO,
    TURNO_TEMPLATE_TURNO_CONSULTORIO,
)
